<a href="https://colab.research.google.com/github/AhmedGS/pytorch_tutorial/blob/master/01_introduction/0_1pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load libraries

In [0]:
import torch
import numpy as np
import pandas as pd

In [0]:
a = torch.tensor([7,5,4,8,5], dtype=torch.int32)

In [0]:
a.dtype

torch.int64

In [0]:
a.type()

'torch.LongTensor'

In [0]:
a = torch.tensor([7,5,4,8,5], dtype=torch.int32)
print(a.dtype)

torch.int32


In [0]:
b = torch.FloatTensor([0.1, 0.3, 5.9])

In [0]:
b.type()

'torch.FloatTensor'

In [0]:
c = b.type(torch.FloatTensor)
c.dtype

torch.float32

In [0]:
a.size()

torch.Size([5])

In [0]:
a.ndimension()

1

In [0]:
a_col = a.view(5, 1)
a_col

tensor([[7],
        [5],
        [4],
        [8],
        [5]], dtype=torch.int32)

In [0]:
a_col = a.view(-1, 1)
a_col

tensor([[7],
        [5],
        [4],
        [8],
        [5]], dtype=torch.int32)

In [0]:
a_col.ndimension()

2

In [0]:
np_array = np.array([0.1, 2.5, 3.9])
torch_tensor = torch.from_numpy(np_array)
bake_to_np = torch_tensor.numpy()

In [0]:
pandas_series = pd.Series([0.1, 2.5, 3.9])
pandas_to_torch = torch.from_numpy(pandas_series.values)
pandas_to_torch

tensor([0.1000, 2.5000, 3.9000], dtype=torch.float64)

In [0]:
my_tensor = torch.tensor([0,1,2,3])
torch_to_list = my_tensor.tolist()
torch_to_list

[0, 1, 2, 3]

In [0]:
c = torch.tensor([0,1,2,3])
print(c)
c[0] = 100
print(c)
print(c[:-2])

tensor([0, 1, 2, 3])
tensor([100,   1,   2,   3])
tensor([100,   1])


In [0]:
u = torch.tensor([2,10])
v = torch.tensor([5,33])
z = u + v
z

tensor([ 7, 43])

In [0]:
z = 2 * u
z

tensor([ 4, 20])

In [0]:
z = u * v
z

tensor([ 10, 330])

In [0]:
#dot prodoct
u = torch.tensor([2,10])
v = torch.tensor([5,33])
z = torch.dot(u, v)
z

tensor(340)

In [0]:
u = u + 1
u

tensor([ 3, 11])

In [0]:
a = torch.tensor([2,10], dtype=torch.float32)
a.mean()

tensor(6.)

In [0]:
a.max()

tensor(10.)

In [0]:
torch.linspace(-2, 2, steps=9)

tensor([-2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000,  1.0000,  1.5000,
         2.0000])

In [0]:
a = torch.tensor([[11,12,13], [21,22,23], [31,32,33]])
a.ndimension()

2

In [0]:
a.shape

torch.Size([3, 3])

In [0]:
#number of elements
a.numel()

9

In [0]:
a[1][2]

tensor(23)

In [0]:
a[0, 0:2]

tensor([11, 12])

In [0]:
a = torch.tensor([[0,1,1], [1,0,1]])
b = torch.tensor([[1,1], [1,1], [1,1]])
c = torch.mm(a, b)
print(c)

tensor([[2, 2],
        [2, 2]])


In [0]:
x = torch.tensor(2, dtype=torch.float32, requires_grad=True)
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [0]:
# y = torch.tensor(x ** 2, dtype=torch.float32, requires_grad=True)

/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if __name__ == '__main__':


In [0]:
# to calc the deriv of y
y.backward()

In [0]:
# to eval the derivative of y at x = 2
x.grad

tensor(4.)

In [0]:
y.grad

In [0]:
x = torch.tensor(2, dtype=torch.float32, requires_grad=True)
z = x ** 2 + 2 * x + 1

In [0]:
z.backward()
x.grad

tensor(6.)

In [0]:
# Partial derivatives
#f(u=1, v=2) = uv + u^2

u = torch.tensor(1, dtype=torch.float32, requires_grad=True)
v = torch.tensor(2, dtype=torch.float32, requires_grad=True)

f = u * v + u**2

In [0]:
f.backward()
print(u.grad, v.grad)

tensor(4.) tensor(1.)
